version: '3'

services:
  server:
    build: .
    ports: 
      - '3100:8080'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/usr/src/app
    links:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3101:3306"
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:5.0.2
    ports:
      - "3102:6379"
    restart: always